---
title       : "Analysis of correlated series with `clustcorr` package"
subtitle    : 
author      : Khristian Kotov
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
github:
  user: kkotov 
  repo: talks
url:
  lib:    ../libraries
  assets: ../assets
widgets     : [mathjax]     # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction

Here I describe a project that spinned-off from a recent
[Winton's Machine Learning competition](https://www.kaggle.com/c/the-winton-stock-market-challenge/data).
I am not concerned with outlining the solution or covering some other details of this rather difficult
competition. My main goal is to describe the new R package, that solves a problem of finding correlated
series on a massive scale. There are some other packages on the market such as `amap`, but I found
that these could not cope with size of this problem.

With my R package the resources sitting on my laps were just about sufficient for the exercise,
which is $\mathcal{8}$GB RAM of my $\mathcal{4}$-cores laptop processing $\mathcal{40}\mathrm{K}$ events.
Unfortunately, the quadratic running time and, more importantly for R, quadratic memory footprint
pose a conceptual limitation of the scalability meaning that twice bigger input would render
useless any machine in my reach.

Nonetheless, this R package can be useful for any data analysis that requires finding and grouping 
together correlated events comprising series of measurements (e.g. time series) for a dataset of
up to $\mathcal{O(50\mathrm{K})}$ events.

--- .class #id

## Problem and solution

Formulation of the problem:

* within a single dataset group together all correlated series of measurements 

Solution:

* find all pair correlations and store them in $\mathcal{O}(N^2)$-sized array
* sort the array and iterate over the top correlated elements greater than a predefined threshold
* group pairs of original series corresponding to the array elements selected above 

--- .class #id

## Practical example

```{r, comment = NA, message = F, echo = T}
# installation
require(devtools)
install_github("clustcorr","koskot77")

# clustering random series
require(clustcorr)
sample <- matrix( rnorm(10000), ncol=100 )
setcores(4)
cl <- cluster.correlations(sample,0.5)
length( unique(cl) )
cl <- recluster.correlations(sample,0.3)
length( unique(cl) )

# clustering non-random series
...
```

--- .class #id



## Useful links

https://www.otexts.org/fpp

http://robjhyndman.com/uwafiles/

[Time series characteristics](http://robjhyndman.com/papers/characteristic-based-clustering-for-time-series-data/)

https://www.kaggle.com/c/the-winton-stock-market-challenge/forums/t/18645/congratulations-thoughts-on-the-problem/106378


